install.packages("BiocManager")
BiocManager::install("flowCore")
install.packages("reticulate")
install.packages("glue")
reticulate::install_miniconda()
reticulate::py_install("tensorflow", pip=TRUE, pip_options="--ignore-installed certifi")
reticulate::py_install("/backend", pip=TRUE)
install.packages("R6")
install.packages("stringr")
install.packages("lsa")
install.packages("clValid")
install.packages(c("devtools","colorspace"))
devtools::install_github('exaexa/scattermore')
